### PR TITLE
don't use python hash

### PR DESCRIPTION
**Pull request by BlancRay**
python hash will give different value in different sessions

### CODE REVIEW

**Comment by fmfn** [comment]
The point of the `hash` trick is *precisely* to avoid one hot encoding every possible value. The fact the hash changes between sessions, while not ideal, is ok in the context of this implementation.

**Comment by vladserkoff** [comment]
@fmfn, while it's true that the point of hashing trick is to avoid one-hot encoding, it's expected that features consistently end up in the same bucket. Consider the case when you train, serialize, then load the model in a different environment, you sure want your features to end up in the same buckets as in training, otherwise your learned weights are as good as random, aren't they?

**Comment by fmfn** [comment]
That's a very good point, @vladserkoff . Nevertheless, the fix is not to one-hot-encode features, but to use a consistent hash function, feel free to submit a PR if you decide to fix it. Unfortunately I won't be able to dedicate any time to this repo in the foreseeable future.

**Comment by vladserkoff** [comment]
Haven't checked this PR before commenting, my bad:) I'll see if it's possible to change the hashing function without too much effort.

**Pull request closed without merging**
